### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by dorkix** [avatarkava/beavisbot-dubtrack-fm#113]
Theres new problem thats popping up now, after a while bot stops working and spits out following exception stack : 

<pre>
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:837:11)
    at TCP.onread (net.js:544:26)

**Comment by avatarkava** [comment]
What package does events.js belong to or is that your own code?  I only have one instance of a file with that name (in dubapi/lib/data/) and it doesn't have anywhere near 141 lines.

**Comment by dorkix** [comment]
Sorry for making you search through it , turns out it was a problem where bot is hosted. It seems fixed now. I apologize.
