### ISSUE TITLE
Problem with latest cleverbot node

### ISSUE THREAD

**Issue by dorkix** [avatarkava/beavisbot-dubtrack-fm#116]
Hey it's me again... miss me? Anyway after the latest cleverbot change bot is unable to start with the following message: http://i.imgur.com/MAX25at.png (had to take a pic because i'm stupid and don't know how to properly format on github) . If i revert to before the latest cleverbot node change bot is working fine but writing something to bot returns `<html>`

**Comment by avatarkava** [comment]
Updated for latest release of cleverbot (everything must be wrapped in prepare() now)

11d390e58c62daa5127efc5216f5a2dab5959e87
